let sb, session, companies = [], users = [], metrics = {};
const el = id => document.getElementById(id);
const api = (name, options = {}) => fetch(`/.netlify/functions/${name}`, { ...options, headers: { Authorization: `Bearer ${session.access_token}`, 'Content-Type': 'application/json' } }).then(async response => { const data = await response.json(); if (!response.ok) throw Error(data.error || 'Error'); return data; });
async function start() { const config = await fetch('/.netlify/functions/public-config').then(response => response.json()); sb = supabase.createClient(config.supabaseUrl, config.supabaseAnonKey); boot(); }
async function signIn() { const { error } = await sb.auth.signInWithPassword({ email: el('email').value, password: el('password').value }); el('loginMessage').textContent = error?.message || ''; if (!error) boot(); }
async function logout() { await sb.auth.signOut(); location.reload(); }
async function boot() { session = (await sb.auth.getSession()).data.session; if (!session) return; el('identity').textContent = `Super Admin: ${session.user.email}`; el('login').hidden = true; el('panel').hidden = false; if (!el('profileCard')) { const profile = document.createElement('section'); profile.id = 'profileCard'; profile.className = 'card'; profile.innerHTML = `<h2>Mi perfil</h2><p>${session.user.email}</p><input id="owner-password" type="password" placeholder="Nueva contraseña (mínimo 10 caracteres)"><button onclick="changePassword()">Actualizar contraseña</button><button onclick="logout()">Cerrar sesión</button>`; el('panel').prepend(profile); } companies = (await sb.from('companies').select('*')).data || []; users = await api('company-users'); metrics = (await api('company-metrics')).byCompany || {}; el('active').textContent = companies.filter(company => company.status === 'activa').length; el('suspended').textContent = companies.filter(company => company.status !== 'activa').length; el('coordinators').textContent = users.filter(user => user.role === 'company_admin').length; el('operators').textContent = users.filter(user => user.role === 'operator').length; render(); }
async function changePassword() { const password = el('owner-password').value; if (password.length < 10) return alert('Mínimo 10 caracteres.'); const { error } = await sb.auth.updateUser({ password }); alert(error ? error.message : 'Contraseña actualizada.'); }
function render() { el('operationsGrid').innerHTML=companies.map(company=>{const m=metrics[company.id]||{total:0,open:0,progress:0,confirmation:0,urgent:0};return '<article class="company"><b>'+company.name+'</b><p>'+m.total+' tickets · '+m.open+' nuevos · '+m.progress+' en proceso<br>'+m.confirmation+' esperando cliente · '+m.urgent+' prioritarios</p></article>';}).join(''); el('companyGrid').innerHTML = companies.map(company => `<article class="company"><b>${company.name}</b><p>Plan: ${company.plan}<br>Estado: ${company.status}<br>Licencia: ${company.license_key}</p><select id="status-${company.id}">${['activa', 'suspendida', 'vencida'].map(status => `<option ${status === company.status ? 'selected' : ''}>${status}</option>`).join('')}</select><button onclick="saveCompany('${company.id}')">Guardar estado</button><button onclick="createActivationKey('${company.id}')">Generar clave de instalación</button></article>`).join(''); el('peopleGroups').innerHTML = companies.map(company => `<div class="team"><b>${company.name}</b>${users.filter(user => user.companyId === company.id).map(user => `<div class="user">${user.name} · ${user.email}<select id="active-${user.id}"><option value="true" ${user.active ? 'selected' : ''}>Activo</option><option value="false" ${!user.active ? 'selected' : ''}>Desactivado</option></select><button onclick="saveUser('${user.id}')">Guardar</button><button onclick="resetPassword('${user.id}')">Restablecer clave</button></div>`).join('') || '<small>Sin usuarios</small>'}</div>`).join(''); }
async function saveCompany(id) { try { await api('company-control', { method: 'PATCH', body: JSON.stringify({ id, status: el(`status-${id}`).value }) }); boot(); } catch (error) { alert(error.message); } }
async function saveUser(id) { try { await api('company-users', { method: 'PATCH', body: JSON.stringify({ id, active: el(`active-${id}`).value === 'true' }) }); boot(); } catch (error) { alert(error.message); } }
async function createActivationKey(companyId) { try { const data = await api('tenant-device', { method: 'POST', body: JSON.stringify({ companyId }) }); await navigator.clipboard?.writeText(data.activationKey); prompt('Clave creada. Cópiala y pégala en Configuración del cliente:', data.activationKey); } catch (error) { alert(error.message); } }
async function resetPassword(id) { const password = prompt('Nueva contraseña temporal (mínimo 10 caracteres):'); if (!password || password.length < 10) return; try { await api('company-users', { method: 'PATCH', body: JSON.stringify({ id, password }) }); alert('Contraseña actualizada.'); } catch (error) { alert(error.message); } }
function openCompany() { el('modal').showModal(); }
async function provision() { try { const data = await api('provision-company', { method: 'POST', body: JSON.stringify({ companyName: el('companyName').value, contactName: el('contactName').value, plan: el('plan').value, userLimit: el('userLimit').value, adminName: el('adminName').value, adminEmail: el('adminEmail').value, adminPassword: el('adminPassword').value }) }); el('message').textContent = `Empresa creada. Licencia: ${data.company.license_key}. Clave de instalación: ${data.activationKey}`; boot(); } catch (error) { el('message').textContent = error.message; } }
start();
